### ISSUE TITLE
Multiple constructors for identical types in the module

### ISSUE THREAD

**Issue by rom8726** [ivankorobkov/di#3]
Is there a way to inject multiple constructors of the one type in the module? For example, I have database interface and I want to inject master and slave databases into one module.

**Comment by ivankorobkov** [comment]
No, it is not possible. One type is mapped to one instance. Either use different types, for example:
```go
type DB interface {
}

type SlaveDB interface {
  DB
}
```

Or a composition:
```go
type DBs interface {
  Master() DB
  Slave() DB
}
```
